### ISSUE TITLE
Fail to load

### ISSUE THREAD

**Issue by BenjaminHoegh** [lol-russo/hyperterm-flat-ui#2]
<img width="328" alt="skaermbillede 2017-03-25 kl 14 54 54" src="https://cloud.githubusercontent.com/assets/22152591/24322835/e2f5a5d0-116b-11e7-876e-aab151da988b.png">

Hyper 1.3.1

**Comment by jacklorusso** [comment]
@HawkonDK You need to add `hyperterm-flat-ui` to your plugins - looks like you only entered `hyperterm-flat`. So, your plugins list should look like the following:

```js
plugins: [
    'hyperterm-flat-ui'
]
```

Thanks for raising the issue though, I haven't checked to see if this still works in months! It's running fine in Hyper 1.3.1
